### ISSUE TITLE
Error trying to run example

### ISSUE THREAD

**Issue by matiaspereyra777** [akshaybabloo/Spikes#1]
Hi. 

I have installed spikes, and I'm trying to run the BSA example.
But when I run the code, the line

`print(spikes_bsa.get_spikes())`

gives me an error in the line 80 of encoder.py 

`        features = self.file_reader.time_feature_length() `

The error is 

AttributeError: 'str' object has no attribute 'time_feature_length'

Is there anyone else with the same trouble?

Best regards.

**Comment by akshaybabloo** [comment]
Not sure why you have this problem. How are you setting your data? Is it possible to attach one sample here?

**Comment by matiaspereyra777** [comment]
Thank you for you quick answer!
I am using this example code

`from __future__ import print_function
import os

from Spikes import BSA, TBR

data_location = os.path.abspath('Data')

print('BSA Encoder')
spikes_bsa = BSA(data_location)
print(spikes_bsa.get_spikes())

print('TBR Encoder')
spikes_tbr = TBR(data_location)
print(spikes_tbr.get_spikes())`

Within the downloaded folder from the repository, using the sample data. I have not changed anything. 
I have tried with python 2 and 3, with no success.

What is this 'time_feature_length' ? Does it mean an issue with the data samples?

Regards.

**Comment by akshaybabloo** [comment]
Thanks for this. Looks like there is a bug in the code when using the newer version of the numpy. I'll update it soon.

**Comment by matiaspereyra777** [comment]
OK, thank you for your time.

Regards!

**Comment by cli-ninja** [comment]
Did you solve the bug? Getting the same error here too

**Comment by akshaybabloo** [comment]
I will fix this in the weekend. Sorry for the delay guys!

**Comment by akshaybabloo** [comment]
I have updated the code, try the new API

```python
from spikes import encoder
from spikes.utility import ReadCSV

data = ReadCSV('Data').get_samples()['samples']

bsa = encoder.BSA(data)
print(bsa.get_spikes())

tbr = encoder.TBR(data)
print(tbr.get_spikes())
```

I am also adding better tests. Should be up soon.

**Comment by matiaspereyra777** [comment]
Thank you!

Regards.
