### ISSUE TITLE
How to optimize BSA?

### ISSUE THREAD

**Issue by Tokenmw** [akshaybabloo/Spikes#15]
hello, I have a question. How to optimize BSA?

**Comment by akshaybabloo** [comment]
You will have to write a decoder that converts your spikes to real values. Then compare those values to the original data.

I think there is an implementation of it in the original paper. I haven't implemented one.

The. You can use grid search or other optimisation techniques to get the best original data.

**Comment by Tokenmw** [comment]
thans for your reply. I try it.

**Comment by akshaybabloo** [comment]
No problem. If you find a way to do it, PR is welcome.

**Comment by Tokenmw** [comment]
we need all the raw signals to find the best parameters of BSA?

**Comment by akshaybabloo** [comment]
Can you tell me a bit about your dataset? Sample rate, is it temporal data, how many samples you have etc?

**Comment by Tokenmw** [comment]
ok, thanks for your repley. Can I contact you by email to tell you more?

**Comment by akshaybabloo** [comment]
Sure. I'll close this ticket for now
